force-app/main/default/objects/Account/fields/AverageMonthlyVolume__c.field-meta.xml
<CustomField>
    <fullName>AverageMonthlyVolume__c</fullName>
    <defaultValue>0</defaultValue>
    <description>average monthly volume</description>
    <label>AverageMonthlyVolume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <formula>IF(AverageMonthlyVolume__c &lt;= 100000, &quot;SME&quot;,
   IF(AverageMonthlyVolume__c &lt;= 299999, &quot;Tier 3&quot;,
    IF(AverageMonthlyVolume__c &lt;= 999999, &quot;Tier 2&quot;, &quot;Tier 1&quot;
       )  
      ) 
    )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/volumes__c.field-meta.xml
<CustomField>
    <fullName>volumes__c</fullName>
    <description>average monthly volume processed over the last 12 months</description>
    <label>volumes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Volume__c/Volume__c.object-meta.xml
<CustomObject>
    <label>Volume</label>
    <nameField>
        <label>Volume Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volumes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volume__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Volumes</relationshipLabel>
    <relationshipName>Volumes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Volume__c/fields/DailyTransaction__c.field-meta.xml
<CustomField>
    <fullName>DailyTransaction__c</fullName>
    <defaultValue>0</defaultValue>
    <label>DailyTransaction</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AccountController.cls
public with sharing class AccountController {

    public static Decimal calculateAverageMonthlyVolume(Decimal annualAmount) {
        if (annualAmount == 0) {
            return 0;
        }
        return annualAmount / 12;
    }
    
    @AuraEnabled
    public static String AverageMonthlyVolume(String accountId, Integer daysAgo, Boolean isUpdate){
        Response res = new Response();
        Decimal volumeCurrency = 0.0;
        
        if(daysAgo == null) daysAgo = 365;
        
        String queryStr = 'SELECT Id, Name, AverageMonthlyVolume__c,Tier__c,'+
            ' (select Id, CreatedDate, DailyTransaction__c FROM Volumes__r WHERE CreatedDate >= N_DAYS_AGO: ' + daysAgo + ' ) FROM Account ';
        if(String.isNotEmpty(accountId)) queryStr += 'WHERE Id = \''+accountId+'\' ';
        
        try {
        List<Account> accounts = (List<Account>)Database.query(queryStr);
        System.debug('AverageMonthlyVolume accounts: ' + accounts);
        List<Account> accountsToUpdate = new List<Account>();
            res.accountDetails = new List<AccountDetails>();
            for (Account acc : accounts) {
                AccountDetails accDetails = new AccountDetails();
                volumeCurrency = 0.0;
                
                for (Volume__c volume : acc.Volumes__r) {
                    volumeCurrency += volume.DailyTransaction__c;
                }
                
                Decimal averageMonthlyVolume = calculateAverageMonthlyVolume(volumeCurrency);
                acc.AverageMonthlyVolume__c = averageMonthlyVolume;
                
                accDetails.volumeCurrency = volumeCurrency;
                accDetails.avgVolumeCurrency = averageMonthlyVolume;
                accDetails.Name = acc.Name;
                
                res.accountDetails.add(accDetails);
                System.debug('AverageMonthlyVolume accDetails: ' + accDetails);
                accountsToUpdate.add(acc);
            }
            
            if (!accountsToUpdate.isEmpty() && isUpdate) {
                update accountsToUpdate;
                res.status = 'Success';
                res.message = 'Average monthly volume updated';
                
            }

        } catch (Exception ex) {
            System.debug('AccountController: err ' + ex.getMessage());
            res.status = 'Error: ';
            res.message = ex.getMessage();
        }
        System.debug('AverageMonthlyVolume res: ' + res);
        return JSON.serialize(res);
    }
    
    @TestVisible
    private class Response {
        private String status;
        private String message;
        private List<AccountDetails> accountDetails;
    }
    
    private class AccountDetails {
        private Decimal volumeCurrency;
        private Decimal avgVolumeCurrency;
        private String name;
    }
    
}